version: "3.8"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017-27019
    volumes:
      - ./data:/data/db
